FROM python:3.12-slim

RUN apt-get update && apt-get install -y ca-certificates 

EXPOSE 9001

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org -r requirements.txt

# install gunicorn
RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org gunicorn

WORKDIR /app
COPY ./app /app

#crete folder localdocs and index in app
RUN mkdir /app/localdocs
RUN mkdir /app/index

# Add /app to PYTHONPATH
ENV PYTHONPATH=/app:$PYTHONPATH

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

CMD ["gunicorn", "--bind", "0.0.0.0:9001", "-k", "uvicorn.workers.UvicornWorker", "main:app"]
